package servent.message;

public enum MessageType {
	NEW_NODE, SUBSCRIBE, BACKUPKEY, BUY, INFO, NOTIFYSUBSCRIBERS, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON, PING, PONG, ASKPING, ASKPONG, DEADNODE
}
